variables:
  buildArgs: '-c Release'
  testArgs: '$(buildArgs) -f netcoreapp3.1 --no-build'


jobs:
- job: 'MSBuild'
  pool:
    vmImage: 'windows-latest'
  steps:
  - powershell: |
     (new-object Net.WebClient).DownloadString("https://raw.github.com/tom-englert/BuildScripts/master/BuildScripts.ps1") | iex
     Project-SetVersion "Directory.Build.props"  | Build-AppendVersionToBuildNumber
    displayName: 'Patch version'
  - task: MSBuild@1
    displayName: 'Build Solution'
    inputs:
      solution: 'Fody.sln'
      platform: 'any cpu'
      configuration: 'release'
      msbuildArguments: '-restore'
      clean: true
  - task: VSTest@2
    displayName: 'VsTest - testAssemblies'
    inputs:
      testAssemblyVer2: |
       **\release\*test*.dll
       !**\obj\**
      platform: 'any cpu'
      configuration: 'release'
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: 'nugets\*.nupkg'
      TargetFolder: '$(build.artifactstagingdirectory)'
      flattenFolders: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: nuget'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: nuget


- job: 'DotnetBuild'
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Build Fody'
    inputs:
      command: 'build'
      projects: 'Fody.sln'
      arguments: $(buildArgs)
  - task: DotNetCoreCLI@2
    displayName: 'Test Fody'
    inputs:
      command: 'test'
      projects: 'Fody.sln'
      arguments: $(buildArgs)
  - task: DotNetCoreCLI@2
    displayName: 'Build Integration'
    inputs:
      command: 'build'
      projects: 'Integration\Integration.sln'
      arguments: $(buildArgs)
  - task: DotNetCoreCLI@2
    displayName: 'Test Integration'
    inputs:
      command: 'test'
      projects: 'Integration\Integration.sln'
      arguments: $(buildArgs)


- job: 'DotnetBuild_Mac'
  pool:
    vmImage: 'macOS-latest'
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Build Fody'
    inputs:
      command: 'build'
      projects: 'Fody.sln'
      arguments: $(buildArgs)
  - task: DotNetCoreCLI@2
    displayName: 'Test Fody'
    enabled: false # fody tests currently do not run on mac/linux
    inputs:
      command: 'test'
      projects: 'Fody.sln'
      arguments: $(testArgs)
  - task: DotNetCoreCLI@2
    displayName: 'Build Integration'
    inputs:
      command: 'build'
      projects: 'Integration/Integration.sln'
      arguments: $(buildArgs)
  - task: DotNetCoreCLI@2
    displayName: 'Test Integration'
    inputs:
      command: 'test'
      projects: 'Integration/Integration.sln'
      arguments: $(testArgs)


- job: 'DotnetBuild_Linux'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Build Fody'
    inputs:
      command: 'build'
      projects: 'Fody.sln'
      arguments: $(buildArgs)
  - task: DotNetCoreCLI@2
    displayName: 'Test Fody'
    enabled: false # fody tests currently do not run on mac/linux
    inputs:
      command: 'test'
      projects: 'Fody.sln'
      arguments: $(testArgs)
  - task: DotNetCoreCLI@2
    displayName: 'Build Integration'
    inputs:
      command: 'build'
      projects: 'Integration/Integration.sln'
      arguments: $(buildArgs)
  - task: DotNetCoreCLI@2
    displayName: 'Test Integration'
    inputs:
      command: 'test'
      projects: 'Integration/Integration.sln'
      arguments: $(testArgs)

- job: 'Integration_VS2017'
  dependsOn: 'MSBuild'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'Nuget'
      downloadPath: './PackageIntegrationTest'
  - task: VSBuild@1
    displayName: 'Build solution'
    inputs:
      solution: 'PackageIntegrationTest/PackageIntegrationTest.sln'
      vsVersion: '15.0'
      msbuildArgs: '-restore'
      platform: 'any cpu'
      configuration: 'release'
  - task: VSTest@2
    displayName: 'Test solution'
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\*test*.dll
        !**\*TestAdapter.dll
        !**\obj\**
      searchFolder: '$(System.DefaultWorkingDirectory)/PackageIntegrationTest'
      vsTestVersion: '15.0'
